package com.mytrip.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import jakarta.validation.constraints.PositiveOrZero;
import jakarta.persistence.Transient;

import java.math.BigDecimal;
import java.math.RoundingMode;

/**
 * Represents a road trip planned through the MyTrip application.
 *
 * A Trip stores route information, vehicle fuel information,
 * expenses, and the traveler's budget.
 */
@Entity
@Table(name = "trips")
public class Trip {

    /** Unique identifier generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    /** User-provided name for the trip. */
    @NotBlank(message = "Trip name is required.")
    private String tripName;

    /** Email address of the traveler who owns the current trip. */
    @NotBlank(message = "Owner email is required.")
    private String ownerEmail;

    /** Location where the trip begins. */
    @NotBlank(message = "Starting location is required.")
    private String startLocation;

    /** Optional stop between the start and destination. */
    private String waypoint;

    /** Final destination of the trip. */
    @NotBlank(message = "Destination is required.")
    private String destination;

    /** Total driving distance in miles. */
    @NotNull(message = "Distance is required.")
    @PositiveOrZero(message = "Distance cannot be negative.")
    private BigDecimal distanceMiles;

    /** Vehicle fuel efficiency in miles per gallon. */
    @NotNull(message = "Vehicle MPG is required.")
    @Positive(message = "Vehicle MPG must be greater than zero.")
    private BigDecimal vehicleMpg;

    /** Estimated price of one gallon of fuel. */
    @NotNull(message = "Fuel price is required.")
    @PositiveOrZero(message = "Fuel price cannot be negative.")
    private BigDecimal fuelPrice;

    /** Maximum amount the traveler wants to spend. */
    @NotNull(message = "Budget is required.")
    @PositiveOrZero(message = "Budget cannot be negative.")
    private BigDecimal budget;

    /** Estimated lodging expenses. */
    @NotNull
    @PositiveOrZero(message = "Lodging cost cannot be negative.")
    private BigDecimal lodgingCost = BigDecimal.ZERO;

    /** Estimated activity expenses. */
    @NotNull
    @PositiveOrZero(message = "Activity cost cannot be negative.")
    private BigDecimal activityCost = BigDecimal.ZERO;

    /**
     * Constructs an empty Trip.
     */
    public Trip() {
    }

    /**
     * Calculates the estimated fuel cost.
     *
     * @return estimated fuel cost rounded to two decimal places
     * @throws IllegalStateException if distance, MPG, or fuel price is invalid
     */
    public BigDecimal calculateFuelCost() {
        validateCalculationData();

        BigDecimal gallonsNeeded = distanceMiles.divide(
                vehicleMpg,
                6,
                RoundingMode.HALF_UP
        );

        return gallonsNeeded
                .multiply(fuelPrice)
                .setScale(2, RoundingMode.HALF_UP);
    }

    /**
     * Calculates the total estimated trip cost.
     *
     * @return combined fuel, lodging, and activity expenses
     */
    public BigDecimal calculateTotalCost() {
        return calculateFuelCost()
                .add(valueOrZero(lodgingCost))
                .add(valueOrZero(activityCost))
                .setScale(2, RoundingMode.HALF_UP);
    }

    /**
     * Calculates how far under or over budget the trip is.
     *
     * A positive result means the trip is under budget.
     * A negative result means the trip is over budget.
     *
     * @return budget minus the total estimated cost
     * @throws IllegalStateException if no budget has been provided
     */
    public BigDecimal calculateBudgetDifference() {
        if (budget == null) {
            throw new IllegalStateException("Budget is required.");
        }

        return budget
                .subtract(calculateTotalCost())
                .setScale(2, RoundingMode.HALF_UP);
    }

    /**
     * Returns the estimated fuel cost for JSON responses.
     *
     * @return calculated fuel cost
     */
    @Transient
    public BigDecimal getFuelCost() {
        return calculateFuelCost();
    }

    /**
     * Returns the total estimated trip cost for JSON responses.
     *
     * @return calculated total cost
     */
    @Transient
    public BigDecimal getTotalCost() {
        return calculateTotalCost();
    }

    /**
     * Returns the amount remaining in the budget.
     *
     * A negative result means the trip exceeds the budget.
     *
     * @return budget minus total cost
     */
    @Transient
    public BigDecimal getBudgetDifference() {
        return calculateBudgetDifference();
    }

    /**
     * Determines whether the estimated trip cost is within budget.
     *
     * @return true when the total cost is equal to or below the budget
     */
    public boolean isUnderBudget() {
        return calculateBudgetDifference().compareTo(BigDecimal.ZERO) >= 0;
    }

    private void validateCalculationData() {
        if (distanceMiles == null || distanceMiles.signum() < 0) {
            throw new IllegalStateException(
                    "Distance must be zero or greater."
            );
        }

        if (vehicleMpg == null || vehicleMpg.signum() <= 0) {
            throw new IllegalStateException(
                    "Vehicle MPG must be greater than zero."
            );
        }

        if (fuelPrice == null || fuelPrice.signum() < 0) {
            throw new IllegalStateException(
                    "Fuel price must be zero or greater."
            );
        }
    }

    public String getOwnerEmail() {
        return ownerEmail;
    }

    public void setOwnerEmail(String ownerEmail) {
        this.ownerEmail = ownerEmail;
    }

    private BigDecimal valueOrZero(BigDecimal value) {
        return value == null ? BigDecimal.ZERO : value;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTripName() {
        return tripName;
    }

    public void setTripName(String tripName) {
        this.tripName = tripName;
    }

    public String getStartLocation() {
        return startLocation;
    }

    public void setStartLocation(String startLocation) {
        this.startLocation = startLocation;
    }

    public String getWaypoint() {
        return waypoint;
    }

    public void setWaypoint(String waypoint) {
        this.waypoint = waypoint;
    }

    public String getDestination() {
        return destination;
    }

    public void setDestination(String destination) {
        this.destination = destination;
    }

    public BigDecimal getDistanceMiles() {
        return distanceMiles;
    }

    public void setDistanceMiles(BigDecimal distanceMiles) {
        this.distanceMiles = distanceMiles;
    }

    public BigDecimal getVehicleMpg() {
        return vehicleMpg;
    }

    public void setVehicleMpg(BigDecimal vehicleMpg) {
        this.vehicleMpg = vehicleMpg;
    }

    public BigDecimal getFuelPrice() {
        return fuelPrice;
    }

    public void setFuelPrice(BigDecimal fuelPrice) {
        this.fuelPrice = fuelPrice;
    }

    public BigDecimal getBudget() {
        return budget;
    }

    public void setBudget(BigDecimal budget) {
        this.budget = budget;
    }

    public BigDecimal getLodgingCost() {
        return lodgingCost;
    }

    public void setLodgingCost(BigDecimal lodgingCost) {
        this.lodgingCost = lodgingCost;
    }

    public BigDecimal getActivityCost() {
        return activityCost;
    }

    public void setActivityCost(BigDecimal activityCost) {
        this.activityCost = activityCost;
    }

    // Getters and setters will go below this line.
}